# -*- coding: utf-8 -*-
"""IoT Air Quality Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sh6CVyB3SfNCvL1D-26N9pk7GxDLC4kr
"""

"""
IoT-Enabled Air Quality Monitoring System
-----------------------------------------
A professional Streamlit dashboard simulating real-time IoT sensor data
for environmental monitoring. It includes live visualizations, safety alerts,
and historical data logging.

Prerequisites:
    pip install streamlit pandas numpy plotly

Usage:
    streamlit run app.py
"""


import streamlit as st
import pandas as pd
import numpy as np
import time
from datetime import datetime, timedelta
import plotly.graph_objects as go
import plotly.express as px

# --- Configuration & Setup ---
st.set_page_config(
    page_title="IoT Air Quality Monitor",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Constants & Thresholds
LOCATIONS = ["Sector 29, Gurugram", "Cyber City", "Udyog Vihar", "Golf Course Road"]
AQI_THRESHOLDS = {
    "Good": (0, 50, "green"),
    "Moderate": (51, 100, "yellow"),
    "Unhealthy for Sensitive Groups": (101, 150, "orange"),
    "Unhealthy": (151, 200, "red"),
    "Very Unhealthy": (201, 300, "purple"),
    "Hazardous": (301, 500, "maroon")
}

# --- State Initialization ---
# We use st.session_state to persist historical data across app reruns (simulating a database)
if 'history' not in st.session_state:
    st.session_state.history = pd.DataFrame(
        columns=['Timestamp', 'Location', 'AQI', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'CO2 (ppm)', 'Temp (°C)', 'Humidity (%)']
    )

# --- Helper Functions ---
def generate_sensor_data(location):
    """Simulates realistic IoT sensor readings based on the selected location."""
    # Base variations to make locations look slightly different
    loc_factor = LOCATIONS.index(location) * 15

    # Introduce some random noise to simulate real sensors
    aqi = int(np.random.normal(120 + loc_factor, 20))
    pm25 = round(np.random.normal(55 + (loc_factor*0.5), 10), 1)
    pm10 = round(np.random.normal(110 + (loc_factor*0.8), 15), 1)
    co2 = int(np.random.normal(450 + loc_factor, 30))
    temp = round(np.random.normal(28, 2), 1)
    humidity = int(np.random.normal(60, 5))

    # Ensure values don't drop below realistic minimums
    return {
        'Timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'Location': location,
        'AQI': max(10, aqi),
        'PM2.5 (µg/m³)': max(5.0, pm25),
        'PM10 (µg/m³)': max(10.0, pm10),
        'CO2 (ppm)': max(400, co2),
        'Temp (°C)': temp,
        'Humidity (%)': max(0, min(100, humidity))
    }

def get_aqi_category(aqi_value):
    """Determines the AQI category and color based on standard EPA thresholds."""
    for category, (low, high, color) in AQI_THRESHOLDS.items():
        if low <= aqi_value <= high:
            return category, color
    return "Hazardous", "maroon" # Default for >500

def create_gauge_chart(value, title, max_val, color):
    """Generates a Plotly gauge chart for KPIs."""
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=value,
        title={'text': title},
        gauge={
            'axis': {'range': [None, max_val]},
            'bar': {'color': color},
            'steps': [
                {'range': [0, max_val*0.5], 'color': "lightgray"},
                {'range': [max_val*0.5, max_val*0.8], 'color': "gray"}
            ],
            'threshold': {
                'line': {'color': "red", 'width': 4},
                'thickness': 0.75,
                'value': max_val * 0.9
            }
        }
    ))
    fig.update_layout(height=250, margin=dict(l=10, r=10, t=40, b=10))
    return fig

# --- UI Layout ---

# Sidebar Controls
st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3203/3203071.png", width=80)
st.sidebar.title("System Controls")
selected_location = st.sidebar.selectbox("📍 Select Monitoring Node", LOCATIONS)
is_live = st.sidebar.toggle("🔴 Enable Live Monitoring", value=False)
refresh_rate = st.sidebar.slider("Refresh Rate (Seconds)", min_value=1, max_value=10, value=3)

st.sidebar.markdown("---")
st.sidebar.subheader("Alert Thresholds")
alert_aqi = st.sidebar.number_input("AQI Alert Level", value=150)
alert_pm25 = st.sidebar.number_input("PM2.5 Alert Level", value=55.0)

# Main Dashboard Header
st.title("☁️ IoT-Enabled Air Quality Monitoring System")
st.markdown("Real-time monitoring, visualization, and alerting for environmental health.")

# Generate/Fetch new data
new_data = generate_sensor_data(selected_location)
new_row = pd.DataFrame([new_data])

# Append to history
st.session_state.history = pd.concat([st.session_state.history, new_row], ignore_index=True)

# Keep only the last 100 records in memory to prevent app slowdown
if len(st.session_state.history) > 100:
    st.session_state.history = st.session_state.history.tail(100)

current_aqi = new_data['AQI']
category, cat_color = get_aqi_category(current_aqi)

# --- Alerts Section ---
alert_container = st.container()
with alert_container:
    if current_aqi >= alert_aqi:
        st.error(f"🚨 **URGENT ALERT**: AQI at {selected_location} has reached {current_aqi} ({category}). Please take precautionary measures.")
    elif new_data['PM2.5 (µg/m³)'] >= alert_pm25:
        st.warning(f"⚠️ **WARNING**: PM2.5 levels are unusually high ({new_data['PM2.5 (µg/m³)']}).")
    else:
        st.success(f"✅ Air quality at {selected_location} is currently within safe parameters.")

st.markdown("---")

# --- Key Performance Indicators (KPIs) ---
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.plotly_chart(create_gauge_chart(current_aqi, "Air Quality Index (AQI)", 500, cat_color), use_container_width=True)
    st.markdown(f"<h3 style='text-align: center; color: {cat_color};'>{category}</h3>", unsafe_allow_html=True)

with col2:
    st.plotly_chart(create_gauge_chart(new_data['PM2.5 (µg/m³)'], "PM2.5 (µg/m³)", 250, "#3498db"), use_container_width=True)

with col3:
    st.plotly_chart(create_gauge_chart(new_data['CO2 (ppm)'], "CO2 (ppm)", 2000, "#9b59b6"), use_container_width=True)

with col4:
    # Use standard metrics for environmentals
    st.metric(label="Temperature", value=f"{new_data['Temp (°C)']} °C", delta="-0.5 °C" if np.random.rand() > 0.5 else "0.5 °C")
    st.metric(label="Humidity", value=f"{new_data['Humidity (%)']} %", delta="-2 %" if np.random.rand() > 0.5 else "2 %")

st.markdown("---")

# --- Real-Time Data Visualization ---
st.subheader("📈 Real-Time Trend Analysis")

# Filter history for current location
loc_history = st.session_state.history[st.session_state.history['Location'] == selected_location]

if len(loc_history) > 1:
    col_chart1, col_chart2 = st.columns(2)

    with col_chart1:
        fig_aqi = px.line(loc_history, x='Timestamp', y='AQI', title="AQI Over Time", markers=True)
        fig_aqi.update_layout(xaxis_title="Time", yaxis_title="AQI Level")
        # Add threshold line
        fig_aqi.add_hline(y=alert_aqi, line_dash="dash", line_color="red", annotation_text="Alert Threshold")
        st.plotly_chart(fig_aqi, use_container_width=True)

    with col_chart2:
        fig_pm = px.line(loc_history, x='Timestamp', y=['PM2.5 (µg/m³)', 'PM10 (µg/m³)'], title="Particulate Matter Over Time", markers=True)
        fig_pm.update_layout(xaxis_title="Time", yaxis_title="Concentration (µg/m³)", legend_title_text="Parameter")
        st.plotly_chart(fig_pm, use_container_width=True)
else:
    st.info("Gathering data to plot trends. Please wait for the next reading...")

st.markdown("---")

# --- Historical Records & Export ---
st.subheader("🗄️ Historical Records")
st.dataframe(st.session_state.history.sort_values(by="Timestamp", ascending=False), use_container_width=True)

# CSV Export Feature
csv = st.session_state.history.to_csv(index=False).encode('utf-8')
st.download_button(
    label="📥 Download Data as CSV",
    data=csv,
    file_name=f"air_quality_log_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
    mime='text/csv',
)

# --- Live Update Logic ---
if is_live:
    time.sleep(refresh_rate)
    st.rerun()